name: Playwright Test Suite (Sharded)
on:
  workflow_dispatch:
  schedule:
    # Run every day at 10:00 AM Uruguay time (UTC-3)
    # GitHub Actions uses UTC, so 10:00 AM UTC-3 = 13:00 UTC
    - cron: '0 13 * * *'

jobs:
  test:
    name: Playwright Test Suite - Shard ${{ matrix.shard }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests (Chromium only, sharded)
      run: npx playwright test --project=chromium --shard=${{ matrix.shard }}/4
      
    # Upload the HTML report as an artifact for download
    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ github.run_number }}-shard${{ matrix.shard }}
        path: |
          playwright-report/
        retention-days: 30

    # Upload Playwright screenshots as an artifact for failed tests
    - name: Upload Playwright screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-screenshots-${{ github.run_number }}-shard${{ matrix.shard }}
        path: |
          test-results/
          screenshots/
        retention-days: 30

# Note for users:
# - When running locally, use 'npx playwright show-report' to view the HTML report in your browser.
# - On GitHub Actions, download the 'playwright-report' artifact and open 'index.html' locally.
# - Download the 'playwright-screenshots' artifact to view screenshots from failed tests.
# - This workflow runs automatically every day at 10:00 AM Uruguay time (UTC-3)
# - Tests are distributed across 4 parallel shards for faster execution
# - Each shard runs on a separate GitHub Actions runner for maximum efficiency
